/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedBansRouteImport } from './routes/_authed/bans'
import { Route as AuthedCategoriesRouteImport } from './routes/_authed/categories'
import { Route as AuthedCommentsRouteImport } from './routes/_authed/comments'
import { Route as AuthedLabelsRouteImport } from './routes/_authed/labels'
import { Route as AuthedPermissionsRouteImport } from './routes/_authed/permissions'
import { Route as AuthedPoliciesRouteImport } from './routes/_authed/policies'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedTagsRouteImport } from './routes/_authed/tags'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts/index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts/$postId'
import { Route as AuthedPostsNewRouteImport } from './routes/_authed/posts/new'
import { Route as AuthedRolesIndexRouteImport } from './routes/_authed/roles/index'
import { Route as AuthedRolesNameRouteImport } from './routes/_authed/roles/$name'
import { Route as AuthedSessionsIndexRouteImport } from './routes/_authed/sessions/index'
import { Route as AuthedSessionsIdRouteImport } from './routes/_authed/sessions/$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBansRoute = AuthedBansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesRoute = AuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommentsRoute = AuthedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsRoute = AuthedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPermissionsRoute = AuthedPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPoliciesRoute = AuthedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTagsRoute = AuthedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsNewRoute = AuthedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesIndexRoute = AuthedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesNameRoute = AuthedRolesNameRouteImport.update({
  id: '/roles/$name',
  path: '/roles/$name',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionsIndexRoute = AuthedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionsIdRoute = AuthedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthedAuditRoute
  '/bans': typeof AuthedBansRoute
  '/categories': typeof AuthedCategoriesRoute
  '/comments': typeof AuthedCommentsRoute
  '/labels': typeof AuthedLabelsRoute
  '/permissions': typeof AuthedPermissionsRoute
  '/policies': typeof AuthedPoliciesRoute
  '/reports': typeof AuthedReportsRoute
  '/tags': typeof AuthedTagsRoute
  '/users': typeof AuthedUsersRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/roles/$name': typeof AuthedRolesNameRoute
  '/sessions/$id': typeof AuthedSessionsIdRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/roles/': typeof AuthedRolesIndexRoute
  '/sessions/': typeof AuthedSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthedAuditRoute
  '/bans': typeof AuthedBansRoute
  '/categories': typeof AuthedCategoriesRoute
  '/comments': typeof AuthedCommentsRoute
  '/labels': typeof AuthedLabelsRoute
  '/permissions': typeof AuthedPermissionsRoute
  '/policies': typeof AuthedPoliciesRoute
  '/reports': typeof AuthedReportsRoute
  '/tags': typeof AuthedTagsRoute
  '/users': typeof AuthedUsersRoute
  '/': typeof AuthedIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts/new': typeof AuthedPostsNewRoute
  '/roles/$name': typeof AuthedRolesNameRoute
  '/sessions/$id': typeof AuthedSessionsIdRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/roles': typeof AuthedRolesIndexRoute
  '/sessions': typeof AuthedSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/bans': typeof AuthedBansRoute
  '/_authed/categories': typeof AuthedCategoriesRoute
  '/_authed/comments': typeof AuthedCommentsRoute
  '/_authed/labels': typeof AuthedLabelsRoute
  '/_authed/permissions': typeof AuthedPermissionsRoute
  '/_authed/policies': typeof AuthedPoliciesRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/tags': typeof AuthedTagsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/posts/new': typeof AuthedPostsNewRoute
  '/_authed/roles/$name': typeof AuthedRolesNameRoute
  '/_authed/sessions/$id': typeof AuthedSessionsIdRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/roles/': typeof AuthedRolesIndexRoute
  '/_authed/sessions/': typeof AuthedSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/bans'
    | '/categories'
    | '/comments'
    | '/labels'
    | '/permissions'
    | '/policies'
    | '/reports'
    | '/tags'
    | '/users'
    | '/posts/$postId'
    | '/posts/new'
    | '/roles/$name'
    | '/sessions/$id'
    | '/posts/'
    | '/roles/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/bans'
    | '/categories'
    | '/comments'
    | '/labels'
    | '/permissions'
    | '/policies'
    | '/reports'
    | '/tags'
    | '/users'
    | '/'
    | '/posts/$postId'
    | '/posts/new'
    | '/roles/$name'
    | '/sessions/$id'
    | '/posts'
    | '/roles'
    | '/sessions'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/audit'
    | '/_authed/bans'
    | '/_authed/categories'
    | '/_authed/comments'
    | '/_authed/labels'
    | '/_authed/permissions'
    | '/_authed/policies'
    | '/_authed/reports'
    | '/_authed/tags'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/posts/$postId'
    | '/_authed/posts/new'
    | '/_authed/roles/$name'
    | '/_authed/sessions/$id'
    | '/_authed/posts/'
    | '/_authed/roles/'
    | '/_authed/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bans': {
      id: '/_authed/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof AuthedBansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories': {
      id: '/_authed/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/comments': {
      id: '/_authed/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthedCommentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels': {
      id: '/_authed/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthedLabelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/permissions': {
      id: '/_authed/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthedPermissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/policies': {
      id: '/_authed/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthedPoliciesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tags': {
      id: '/_authed/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthedTagsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/new': {
      id: '/_authed/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthedPostsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/': {
      id: '/_authed/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthedRolesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/$name': {
      id: '/_authed/roles/$name'
      path: '/roles/$name'
      fullPath: '/roles/$name'
      preLoaderRoute: typeof AuthedRolesNameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sessions/': {
      id: '/_authed/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthedSessionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sessions/$id': {
      id: '/_authed/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthedSessionsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedBansRoute: typeof AuthedBansRoute
  AuthedCategoriesRoute: typeof AuthedCategoriesRoute
  AuthedCommentsRoute: typeof AuthedCommentsRoute
  AuthedLabelsRoute: typeof AuthedLabelsRoute
  AuthedPermissionsRoute: typeof AuthedPermissionsRoute
  AuthedPoliciesRoute: typeof AuthedPoliciesRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedTagsRoute: typeof AuthedTagsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsNewRoute: typeof AuthedPostsNewRoute
  AuthedRolesNameRoute: typeof AuthedRolesNameRoute
  AuthedSessionsIdRoute: typeof AuthedSessionsIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
  AuthedRolesIndexRoute: typeof AuthedRolesIndexRoute
  AuthedSessionsIndexRoute: typeof AuthedSessionsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedBansRoute: AuthedBansRoute,
  AuthedCategoriesRoute: AuthedCategoriesRoute,
  AuthedCommentsRoute: AuthedCommentsRoute,
  AuthedLabelsRoute: AuthedLabelsRoute,
  AuthedPermissionsRoute: AuthedPermissionsRoute,
  AuthedPoliciesRoute: AuthedPoliciesRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedTagsRoute: AuthedTagsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsNewRoute: AuthedPostsNewRoute,
  AuthedRolesNameRoute: AuthedRolesNameRoute,
  AuthedSessionsIdRoute: AuthedSessionsIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
  AuthedRolesIndexRoute: AuthedRolesIndexRoute,
  AuthedSessionsIndexRoute: AuthedSessionsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
